/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlockchainWill } from "./BlockchainWill";
export * as factories from "./factories";
export { BlockchainWill__factory } from "./factories/BlockchainWill__factory";
